from __future__ import annotations

import csv
import json
import tempfile
import unittest
from html.parser import HTMLParser
from pathlib import Path

from agent_trace_studio.parser import analyze_journals
from agent_trace_studio.report import write_report
from helpers import write_journal


class ReportTest(unittest.TestCase):
    def test_writes_self_contained_dashboard_and_exports(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            journal = root / 'session.jsonl'
            write_journal(journal, include_malformed=True)
            result = analyze_journals([journal])

            bundle = write_report(result, output_dir=root / 'dashboard')

            html = bundle.index_path.read_text(encoding='utf-8')
            manifest = json.loads(bundle.manifest_path.read_text(encoding='utf-8'))
            analysis = json.loads(bundle.analysis_path.read_text(encoding='utf-8'))

        self.assertIn('<h1 id="dashboard-title">Agent Trace Studio</h1>', html)
        self.assertIn('<h2>Agent execution trace</h2>', html)
        self.assertNotIn('<h2 id="studio-panel-title">', html)
        self.assertIn('dashboard-data', html)
        self.assertNotIn('class="tab-button', html)
        self.assertNotIn('id="analysis-tabs"', html)
        self.assertNotIn('data-tab="trace"', html)
        self.assertNotIn('data-tab="tools"', html)
        self.assertNotIn('data-tab="overview"', html)
        self.assertNotIn('data-tab="sessions"', html)
        self.assertNotIn('data-tab="turns"', html)
        self.assertNotIn('data-tab="data"', html)
        self.assertIn('id="session-id-form"', html)
        self.assertIn('id="session-id"', html)
        self.assertIn('id="load-session-id-button"', html)
        self.assertIn('id="source-loader-status"', html)
        self.assertIn('Read-only report. Open Agent Trace Studio through its local server to add sources.', html)
        self.assertIn("document.getElementById('session-id').disabled = unavailable;", html)
        self.assertIn("document.getElementById('session-path').disabled = unavailable;", html)
        self.assertIn('Codex session ID', html)
        self.assertIn('id="session-path"', html)
        self.assertIn('id="upload-button"', html)
        self.assertIn('id="trace-session-select"', html)
        self.assertIn('aria-label="Supported trace adapters"', html)
        self.assertIn('>Claude Code</span>', html)
        self.assertIn('>LangGraph</span>', html)
        self.assertIn('>OpenAI Agents SDK</span>', html)
        self.assertIn('>Custom runner</span>', html)
        self.assertIn('id="current-source-adapter"', html)
        self.assertIn('id="current-source-turn-count"', html)
        self.assertIn('id="current-source-event-count"', html)
        self.assertIn('function traceAdapterLabel(trace)', html)
        self.assertIn('const candidates = [liveSource?.adapter, summary?.originator, summary?.source]', html)
        self.assertIn('id="live-monitor"', html)
        self.assertIn('id="live-audit-start"', html)
        self.assertIn('Start live monitor &amp; audit', html)
        self.assertIn("'/api/live/audit-actions/message'", html)
        self.assertIn('id="audit-rule-action-enabled"', html)
        self.assertIn('id="audit-rule-action-message"', html)
        self.assertIn('automatic_action: automaticAction', html)
        self.assertIn('id="live-state"', html)
        self.assertIn('id="follow-live"', html)
        self.assertIn('id="trace-workbench"', html)
        self.assertIn('id="floating-workspace"', html)
        self.assertIn('id="agent-selection-panel"', html)
        self.assertIn('id="source-workspace"', html)
        self.assertNotIn('id="studio-panel"', html)
        self.assertNotIn('id="studio-panel-toggle"', html)
        self.assertIn('id="source-dialog"', html)
        self.assertIn('id="add-source-button"', html)
        self.assertIn('id="qa-context-details"', html)
        self.assertIn('id="qa-run-details"', html)
        self.assertIn('data-floating-handle', html)
        self.assertIn('id="trace-turn-resizer"', html)
        self.assertIn('id="trace-event-resizer"', html)
        self.assertIn('id="trace-height-resizer"', html)
        self.assertIn('multiple hidden', html)
        self.assertNotIn('id="runtime-badge"', html)
        self.assertLess(html.index('id="current-source"'), html.index('id="trace"'))
        self.assertIn('id="trace-tool-total"', html)
        self.assertIn('id="trace-tool-unique"', html)
        self.assertIn('id="trace-tool-chips"', html)
        self.assertNotIn('id="tools"', html)
        self.assertNotIn('id="tool-bars"', html)
        self.assertNotIn('id="tool-table"', html)
        self.assertIn('id="qa-form"', html)
        self.assertIn('id="qa-stop"', html)
        self.assertIn('id="qa-configure-button"', html)
        self.assertIn('id="qa-config-dialog"', html)
        self.assertIn('id="qa-api-key"', html)
        self.assertIn('id="qa-remember-key"', html)
        self.assertIn('id="qa-vault-password"', html)
        self.assertIn('id="qa-vault-password-confirm"', html)
        self.assertIn('id="qa-api-provider"', html)
        self.assertIn('id="qa-api-model-preset"', html)
        self.assertIn('id="agent-context-source"', html)
        self.assertIn('id="agent-context-turn"', html)
        self.assertIn('id="session-brief-panel"', html)
        self.assertIn('id="session-brief-button"', html)
        self.assertIn('id="session-brief-auto"', html)
        self.assertIn('id="session-brief-toggle"', html)
        self.assertIn('aria-controls="session-brief-content"', html)
        self.assertLess(html.index('id="session-brief-panel"'), html.index('id="trace"'))
        self.assertIn('id="agent-context-event"', html)
        self.assertIn('id="agent-context-checkpoint"', html)
        self.assertIn('id="agent-context-analysis-label"', html)
        self.assertIn('id="agent-context-focus-label"', html)
        self.assertIn('id="agent-context-focus"', html)
        self.assertIn('id="agent-context-focus-meta"', html)
        self.assertIn('id="assurance-panel"', html)
        self.assertIn('id="assurance-replay"', html)
        self.assertIn('id="assurance-contract-list"', html)
        self.assertIn('id="assurance-manage"', html)
        self.assertIn('id="assurance-toggle"', html)
        self.assertIn('aria-controls="assurance-content"', html)
        self.assertIn('>Review rules</button>', html)
        self.assertIn('id="audit-rules-dialog"', html)
        self.assertNotIn('Draft with agent', html)
        self.assertNotIn('id="audit-rule-agent-instruction"', html)
        self.assertNotIn('id="audit-rule-agent-submit"', html)
        self.assertNotIn('id="audit-rule-new"', html)
        self.assertNotIn('>New rule</button>', html)
        self.assertNotIn('Create one manually or ask the Studio agent to draft one.', html)
        self.assertIn("element('button', 'command-button', 'Create new rule')", html)
        self.assertIn('id="audit-rule-form"', html)
        self.assertIn('id="audit-rule-review"', html)
        self.assertIn('id="audit-rule-review-content"', html)
        self.assertIn('id="audit-rule-edit"', html)
        self.assertIn('id="audit-rule-cancel-edit"', html)
        self.assertIn('pattern="[a-z][a-z0-9\\-]{2,63}"', html)
        self.assertIn('id="audit-rule-event-tool"', html)
        self.assertIn('id="audit-rule-required-tool"', html)
        self.assertIn('id="qa-highlight-context"', html)
        self.assertIn('id="qa-highlight-label"', html)
        self.assertIn('id="qa-floating-button"', html)
        self.assertIn('id="qa-conversation-popover"', html)
        self.assertIn('id="qa-conversation-close"', html)
        self.assertIn('id="qa-conversation-toggle"', html)
        self.assertIn('aria-controls="qa-context-details qa-conversation-body qa-highlight-context qa-form"', html)
        self.assertIn('id="qa-conversation-status"', html)
        self.assertIn('id="studio-context-menu"', html)
        self.assertIn('id="studio-context-menu-ask"', html)
        self.assertIn('>Ask agent</button>', html)
        self.assertIn('<h2 id="qa-conversation-title">Studio conversation</h2>', html)
        self.assertIn('id="qa-unread-count"', html)
        self.assertIn('title="Open Studio conversation; drag to move"', html)
        self.assertIn('aria-controls="qa-conversation-popover"', html)
        self.assertEqual(html.count('id="qa-messages"'), 1)
        self.assertEqual(html.count('id="qa-form"'), 1)
        self.assertIn('M7.9 20A9 9 0 1 0 4 16.1L2 22Z', html)
        self.assertNotIn('id="selection-context-menu"', html)
        self.assertNotIn('id="selection-ask"', html)
        self.assertGreater(html.index('id="qa-conversation-popover"'), html.index('</main>'))
        self.assertNotIn('id="agent-investigate-button"', html)
        self.assertNotIn('id="agent-extract-memories-button"', html)
        self.assertNotIn('id="agent-audit-parser-button"', html)
        self.assertNotIn('id="agent-customize-dashboard-button"', html)
        self.assertIn('id="agent-harness-select"', html)
        self.assertEqual(html.count('id="agent-harness-select"'), 1)
        self.assertIn('Agent type', html)
        self.assertIn('id="agent-selection-title">Choose agent type</h2>', html)
        self.assertLess(html.index('id="agent-harness-select"'), html.index('id="source-workspace-title"'))
        self.assertLess(html.index('id="agent-harness-select"'), html.index('id="qa-conversation-title"'))
        self.assertIn('id="agent-capability-list"', html)
        self.assertIn('function renderAgentCapabilities(agent)', html)
        self.assertIn("['Audit behavior', Boolean(runtime.audit_rules?.available)]", html)
        self.assertNotIn('id="agent-customize-dialog"', html)
        self.assertNotIn('id="agent-customize-request"', html)
        self.assertNotIn('id="agent-fix-source-button"', html)
        self.assertNotIn('id="agent-audit-actions"', html)
        self.assertNotIn('id="agent-fix-audit-button"', html)
        self.assertIn('<span class="control-label">Message</span>', html)
        self.assertIn('>Send</button>', html)
        self.assertIn('id="agent-run-panel"', html)
        self.assertIn('id="agent-run-label"', html)
        self.assertIn('id="agent-run-session-meta"', html)
        self.assertIn('Fixer session ${runIdentity}', html)
        self.assertIn("' · approval consumed'", html)
        self.assertIn('id="agent-activity"', html)
        self.assertIn('id="agent-activity-list"', html)
        self.assertIn('id="agent-repair-summary"', html)
        self.assertIn('id="agent-run-recovery"', html)
        self.assertIn('id="agent-run-continue"', html)
        self.assertIn('id="agent-run-restart"', html)
        self.assertIn('id="agent-run-discard"', html)
        self.assertIn('id="agent-recovery-instruction"', html)
        self.assertIn('id="agent-recovery-feedback"', html)
        self.assertIn('role="log"', html)
        self.assertIn('Mechanical checks passed', html)
        self.assertIn('Inherited baseline failures', html)
        self.assertIn('inherited_failed_checks', html)
        self.assertIn('Independent review', html)
        self.assertIn('Candidate files', html)
        self.assertIn('What this attempt changed', html)
        self.assertIn('Fixed items', html)
        self.assertIn('Why verification failed', html)
        self.assertNotIn('Latest repair', html)
        self.assertNotIn('Latest verification', html)
        self.assertNotIn('Verification failures', html)
        self.assertIn('details.open = openAttempts.has(attemptKey);', html)
        self.assertNotIn('previousAttemptCount', html)
        self.assertIn('scheduleAgentPoll(runId, 2000)', html)
        self.assertIn('function queueDashboardReload(run)', html)
        self.assertIn('const dashboardReloadMarkers = new Set()', html)
        self.assertIn("document.getElementById('agent-run-activate')", html)
        self.assertIn('qaConversationStorageKey', html)
        self.assertIn('AgentTraceConversationState', html)
        self.assertLess(html.index('AgentTraceConversationState'), html.index('(() => {'))
        self.assertIn('function persistQAConversation()', html)
        self.assertIn('function loadSessionId(sessionId)', html)
        self.assertIn("apiJson('/api/session/id'", html)
        self.assertIn("['user', 'assistant', 'error'].includes(message?.role)", html)
        self.assertIn('function appendAgentRunCompletion(run)', html)
        self.assertIn('qaConversationState.completeWorkflow', html)
        self.assertIn('const completionAdded = appendAgentRunCompletion(run);', html)
        self.assertIn('function renderQAActivity()', html)
        self.assertIn('function qaSuggestedPrompts()', html)
        self.assertIn('function renderQASuggestions(messages, configured)', html)
        self.assertIn("label: 'Investigate this session'", html)
        self.assertIn("label: 'Review selected audit finding'", html)
        self.assertIn("label: 'Customize the dashboard...'", html)
        self.assertIn("prefill: 'Customize the dashboard: '", html)
        self.assertIn('sendAgentMessage(suggestion.prompt);', html)
        self.assertIn('!runtime.qa?.configured || !selectedTrace()', html)
        self.assertIn('!configured || !selectedTrace() || state.qaBusy', html)
        self.assertIn('if (!state.qaMessages.length)', html)
        self.assertNotIn('No messages yet.', html)
        self.assertIn('.qa-suggestion-list {', html)
        self.assertIn('function updateQAActivity(run)', html)
        self.assertIn('qaConversationState.workflowActivity', html)
        self.assertIn('function pollStudioRequestActivity(requestId)', html)
        self.assertIn('function renderQAActivityTimeline(content, record)', html)
        self.assertIn('qaConversationState.normalizeActivityRecord', html)
        self.assertIn("element('details', 'qa-activity-details')", html)
        self.assertIn("details.open = typeof record.expanded === 'boolean' ? record.expanded : !terminal", html)
        self.assertIn('.qa-activity-summary {', html)
        self.assertIn('.qa-message.activity {', html)
        self.assertIn('.qa-message.audit_rule_proposal .audit-rule-proposal {', html)
        self.assertIn('grid-template-columns: minmax(0, 1fr);', html)
        self.assertIn('.qa-message.audit_rule_proposal .audit-rule-proposal-actions {', html)
        self.assertIn('@keyframes qa-live-activity-pulse', html)
        self.assertIn('After verification', html)
        self.assertIn('Approve change and activate', html)
        self.assertIn('authorization.activation_effect', html)
        self.assertIn('function pollDeploymentGeneration()', html)
        self.assertIn("deployment.status === 'promoted'", html)
        self.assertIn("element('h4', '', 'Runtime deployment')", html)
        self.assertIn('function renderDeploymentLifecycle(deployment)', html)
        self.assertIn("['Candidate', 'Verified', 'success'", html)
        self.assertIn("['Health check', healthState[0], healthState[1]", html)
        self.assertIn("['Rollback', rollbackState[0], rollbackState[1]", html)
        self.assertIn('.deployment-lifecycle {', html)
        self.assertIn('window.sessionStorage.setItem(marker', html)
        self.assertIn('Updated dashboard loaded automatically.', html)
        self.assertIn('state.runtimeRetryTimer = window.setTimeout(setupRuntime, 2000)', html)
        self.assertIn('new EventSource(`/api/live/stream?after=${encodeURIComponent(state.liveRevision)}`)', html)
        self.assertNotIn('Agent backend pending', html)
        self.assertIn('Fix and activate local source', html)
        self.assertNotIn('Create fix branch', html)
        self.assertIn('dashboard_state: dashboardState', html)
        self.assertIn('history: state.qaConversationBootstrapped ? [] : relevantHistory', html)
        self.assertIn('conversation_id: state.qaConversationId', html)
        self.assertIn('id="qa-new-conversation"', html)
        self.assertIn('function startNewStudioConversation()', html)
        self.assertIn('function renderMarkdown(value)', html)
        self.assertIn('function renderCheckpointResult(container, result, run, openCheckpoints = new Set())', html)
        self.assertIn('function renderSessionBrief()', html)
        self.assertIn('function refreshSessionBrief()', html)
        self.assertIn('function summarizeSessionCheckpoints({ automatic = false } = {})', html)
        self.assertIn('function reconcileSelectedCheckpoint(brief)', html)
        self.assertIn('sessionBriefAutoUpdateStorageKey', html)
        self.assertIn('sessionBriefCollapsedStorageKey', html)
        self.assertIn('content.hidden = state.sessionBriefCollapsed;', html)
        self.assertIn("renderCollapseToggle(toggle, state.sessionBriefCollapsed, 'session brief');", html)
        self.assertIn('assuranceCollapsedStorageKey', html)
        self.assertIn('content.hidden = state.assuranceCollapsed;', html)
        self.assertIn("renderCollapseToggle(toggle, state.assuranceCollapsed, 'session audit');", html)
        self.assertIn('qaConversationCollapsedStorageKey', html)
        self.assertIn("popover.classList.toggle('collapsed', state.qaConversationCollapsed);", html)
        self.assertIn(
            "renderCollapseToggle(collapseToggle, state.qaConversationCollapsed, 'Studio conversation');", html
        )
        self.assertIn('floatingPanelLayoutStorageKey', html)
        self.assertIn('id="reset-layout"', html)
        self.assertIn('function resetFloatingPanelLayout({ clearSaved = true } = {})', html)
        self.assertIn('window.localStorage.removeItem(floatingPanelLayoutStorageKey)', html)
        self.assertIn("document.getElementById('reset-layout').addEventListener", html)
        self.assertNotIn('studioPanelCollapsedStorageKey', html)
        self.assertIn('function setupFloatingPanels()', html)
        self.assertIn('function bindFloatingPanel(panel)', html)
        self.assertIn('setupRuntime().finally(setupFloatingPanels);', html)
        self.assertIn('#floating-workspace.floating-panels-enabled > [data-floating-panel] {', html)
        self.assertIn('resize: both;', html)
        self.assertIn('representative event detail', html)
        self.assertIn('autoToggle.disabled = state.sessionBriefBusy || !runtime.qa?.configured;', html)
        self.assertIn('const changedSession = target.trace.session_id !== state.traceSessionId;', html)
        self.assertNotIn('renderCheckpointControl()', html)
        self.assertIn('function renderAssurance()', html)
        self.assertIn('function replayAssurance()', html)
        self.assertIn('function refreshAuditRules()', html)
        self.assertIn('function renderAuditRuleDialog()', html)
        self.assertIn('function renderAuditRuleReview(rule)', html)
        self.assertIn('function beginAuditRuleEdit()', html)
        self.assertIn('function cancelAuditRuleEdit()', html)
        self.assertIn('async function approveAuditRuleProposal(', html)
        self.assertIn("response.kind === 'audit_rule_proposal'", html)
        self.assertIn('.audit-rules-dialog {', html)
        self.assertIn('.audit-rule-review {', html)
        self.assertIn('function selectAssuranceEvidence(contract, status, evidence', html)
        self.assertIn("appendCheckpointDetailList(details, 'What the agent did'", html)
        self.assertIn("appendCheckpointDetailList(details, 'Achieved'", html)
        self.assertIn("appendCheckpointDetailList(details, 'Main blockers'", html)
        self.assertIn("appendCheckpointDetailList(details, 'Turns'", html)
        self.assertNotIn("appendAgentResultList(container, 'Decisions'", html)
        self.assertIn('function openQAConversation({ focus = true, expand = true } = {})', html)
        self.assertIn('function toggleQAConversation()', html)
        self.assertIn('function setupQAFloatingDock()', html)
        self.assertIn('function constrainedQAFloatingButtonPosition(left, top)', html)
        self.assertIn('function positionQAConversationNearButton()', html)
        self.assertIn('qaFloatingButtonPositionStorageKey', html)
        self.assertIn('button.setPointerCapture(event.pointerId);', html)
        self.assertIn("if ('ResizeObserver' in window)", html)
        self.assertIn("document.addEventListener('contextmenu', handleSelectionContextMenu)", html)
        self.assertIn('document.body.contains(common)', html)
        self.assertIn("document.getElementById('studio-context-menu-ask').addEventListener", html)
        self.assertIn("openStudioContextMenu(event, { kind: 'highlight', ...context })", html)
        self.assertIn("closest('dialog[open]')", html)
        self.assertIn('if (context.dialog?.open) context.dialog.close();', html)
        self.assertNotIn("common?.closest('#trace-workbench, #agent-run-panel, #qa-messages')", html)
        self.assertNotIn('async function draftAuditRuleWithAgent()', html)
        self.assertNotIn('function beginNewAuditRule()', html)
        self.assertIn('function startAuditRuleDraftInStudio()', html)
        self.assertIn("input.value = 'Create an audit rule: ';", html)
        self.assertNotIn('Create an audit rule that ', html)
        self.assertIn('async function stopStudioAgent()', html)
        self.assertIn("document.getElementById('qa-stop').addEventListener", html)
        self.assertIn('request_id: requestId', html)
        self.assertIn('openQAConversation();', html)
        self.assertIn('.qa-floating-button {', html)
        self.assertIn('.qa-conversation-popover {', html)
        self.assertIn('.qa-floating-button.is-dragging', html)
        self.assertIn(".qa-conversation-popover[data-anchor='above']::after", html)
        self.assertIn('ask_target: askTarget', html)
        self.assertIn('button.dataset.turnId = turn.turn_id;', html)
        self.assertIn('button.dataset.eventSequence = String(event.sequence);', html)
        self.assertIn('renderMarkdown(message.text)', html)
        self.assertIn('safeMarkdownHref', html)
        self.assertIn('qa-markdown-table', html)
        self.assertIn('qa-code-block', html)
        self.assertIn('function navigateToTraceAnchor(turnId, lineNumber)', html)
        self.assertIn('function traceEvidenceLink(value)', html)
        self.assertIn('function appendTraceAnchoredText(parent, value)', html)
        self.assertIn("traceAnchoredElement('span', 'checkpoint-summary-text'", html)
        self.assertIn('appendTraceEvidenceAnchors(evidence, anchors)', html)
        self.assertIn('{ evidence: true }', html)
        self.assertIn("element('a', 'trace-evidence-link'", html)
        self.assertIn('.trace-evidence-link {', html)
        self.assertNotIn('innerHTML', html)
        self.assertNotIn('data-qa-scope', html)
        self.assertNotIn('Full trace', html)
        self.assertNotIn('Selected turn', html)
        self.assertNotIn('TOP_SECRET_TOOL_INPUT', html)
        self.assertNotIn('TOP_SECRET_TOOL_OUTPUT', html)
        self.assertEqual(manifest['schema_version'], 'codex-session-dashboard.v2')
        self.assertFalse(manifest['content_policy']['tool_payloads_embedded'])
        self.assertEqual(analysis['overview']['turns_total'], 2)

    def test_source_dialog_and_chat_own_their_controls(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            journal = root / 'synthetic.jsonl'
            write_journal(journal)
            bundle = write_report(analyze_journals([journal]), output_dir=root / 'dashboard')
            html = bundle.index_path.read_text(encoding='utf-8')

        class Structure(HTMLParser):
            def __init__(self) -> None:
                super().__init__()
                self.stack: list[tuple[str, str | None]] = []
                self.parents: dict[str, list[str | None]] = {}
                self.counts: dict[str, int] = {}

            def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
                node_id = dict(attrs).get('id')
                if node_id:
                    self.parents[node_id] = [item[1] for item in self.stack]
                    self.counts[node_id] = self.counts.get(node_id, 0) + 1
                if tag not in {'input', 'meta', 'link', 'br', 'hr', 'img', 'area', 'base', 'embed', 'source', 'wbr'}:
                    self.stack.append((tag, node_id))

            def handle_endtag(self, tag: str) -> None:
                for index in range(len(self.stack) - 1, -1, -1):
                    if self.stack[index][0] == tag:
                        del self.stack[index:]
                        break

        structure = Structure()
        structure.feed(html)
        self.assertTrue(all(count == 1 for count in structure.counts.values()), 'DOM IDs must remain unique')
        self.assertNotIn('studio-panel', structure.parents)
        self.assertIn('source-workspace', structure.parents['add-source-button'])
        self.assertNotIn('floating-workspace', structure.parents['source-dialog'])
        for control in ('session-id-form', 'path-form', 'upload-button', 'source-dialog-close', 'source-dialog-status'):
            with self.subTest(control=control):
                self.assertIn('source-dialog', structure.parents[control])
        self.assertIn('agent-selection-panel', structure.parents['qa-configure-button'])
        self.assertNotIn('qa-conversation-popover', structure.parents['qa-configure-button'])
        for control in ('qa-context-details', 'qa-run-details', 'qa-form', 'qa-messages'):
            with self.subTest(control=control):
                self.assertIn('qa-conversation-popover', structure.parents[control])
        self.assertIn('qa-conversation-body', structure.parents['qa-messages'])
        for control in ('agent-run-activate', 'agent-run-continue', 'agent-run-restart', 'agent-run-discard'):
            with self.subTest(control=control):
                self.assertIn('qa-run-details', structure.parents[control])
        self.assertIn('qa-context-details', structure.parents['agent-context-source'])
        self.assertIn('qa-context-details', structure.parents['agent-capability-list'])
        self.assertLess(html.index('  setupStudioSurfaces();'), html.index('  setupControls();'))

    def test_embeds_video_aligned_dashboard_theme(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            journal = root / 'session.jsonl'
            write_journal(journal)
            result = analyze_journals([journal])

            bundle = write_report(result, output_dir=root / 'dashboard')
            html = bundle.index_path.read_text(encoding='utf-8')

        self.assertIn('--bg: #fbfaff;', html)
        self.assertIn('--ink: #27213f;', html)
        self.assertIn('--muted: #625c75;', html)
        self.assertIn('--accent: #5f3dc4;', html)
        self.assertIn('--accent-strong: #492a96;', html)
        self.assertIn('--focus-ring: #7048e8;', html)
        self.assertIn('--grid-line: rgb(95 61 196 / 7%);', html)
        self.assertIn('--success-soft: #ebfbee;', html)
        self.assertIn('--warning-soft: #fff9db;', html)
        self.assertIn('--failure-soft: #fff0f6;', html)
        self.assertIn('linear-gradient(var(--grid-line) 1px, transparent 1px)', html)
        self.assertIn('background-size: 32px 32px;', html)
        self.assertIn('main {\n  width: 100%;', html)
        self.assertNotIn('width: min(1680px, 100%);', html)
        self.assertIn('.topbar::before {', html)
        self.assertIn('background: var(--accent);', html)
        self.assertIn('<span class="product-kicker">Local agent trace workbench</span>', html)
        self.assertIn('<h2 id="source-workspace-title">Source workspace</h2>', html)
        self.assertIn('<span class="control-label">Trace workbench</span>', html)
        self.assertIn('.source-workspace-grid {', html)
        self.assertIn('border: 1px solid rgb(95 61 196 / 42%);', html)
        self.assertNotIn('rainbow-gradient', html)
        self.assertNotIn('radial-gradient', html)
        self.assertNotIn('background-clip: text', html)
        self.assertIn('@media (forced-colors: active)', html)
        self.assertIn('outline: 3px solid var(--focus-ring);', html)
        self.assertIn('box-shadow: 0 0 0 3px var(--accent-halo);', html)
        self.assertIn('.qa-markdown-link:hover {\n  color: var(--accent-strong);', html)
        self.assertIn('body ::selection {\n  background: var(--selection);', html)
        self.assertRegex(
            html,
            r'\.qa-remember-option input \{[^}]*accent-color: var\(--accent\);[^}]*\}',
        )
        self.assertNotRegex(
            html,
            r'\.qa-remember-option input \{[^}]*accent-color: var\(--blue\);[^}]*\}',
        )
        self.assertNotIn('--accent: #b42318;', html)
        self.assertNotIn('rgb(50 27 27 /', html)

    def test_writes_opt_in_normalized_trace_without_encrypted_reasoning(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            journal = root / 'session.jsonl'
            write_journal(journal)
            result = analyze_journals([journal], include_trace=True)

            bundle = write_report(result, output_dir=root / 'dashboard')
            html = bundle.index_path.read_text(encoding='utf-8')
            manifest = json.loads(bundle.manifest_path.read_text(encoding='utf-8'))
            analysis = json.loads(bundle.analysis_path.read_text(encoding='utf-8'))

        self.assertIn('Agent execution trace', html)
        self.assertIn('Studio conversation', html)
        self.assertIn('TOP_SECRET_TOOL_INPUT', html)
        self.assertIn('TOP_SECRET_TOOL_OUTPUT', html)
        self.assertNotIn('TOP_SECRET_ENCRYPTED_REASONING', html)
        self.assertTrue(manifest['content_policy']['normalized_trace_events_embedded'])
        self.assertTrue(manifest['content_policy']['tool_payloads_embedded'])
        self.assertFalse(manifest['content_policy']['raw_journal_rows_embedded'])
        self.assertFalse(manifest['content_policy']['encrypted_reasoning_embedded'])
        self.assertEqual(len(analysis['traces']), 1)

    def test_escapes_hostile_title_inside_html_and_json_script(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            journal = root / 'session.jsonl'
            write_journal(journal)
            result = analyze_journals([journal])
            title = '</script><script>globalThis.bad = true</script>'

            bundle = write_report(result, output_dir=root / 'dashboard', title=title)
            html = bundle.index_path.read_text(encoding='utf-8')

        self.assertNotIn(title, html)
        self.assertNotIn('<script>globalThis.bad', html)
        self.assertIn(r'\u003c/script\u003e', html)

    def test_custom_trace_label_does_not_replace_product_brand(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            journal = root / 'session.jsonl'
            write_journal(journal)
            result = analyze_journals([journal])

            bundle = write_report(result, output_dir=root / 'dashboard', title='Async Cancellation Agent Run')
            html = bundle.index_path.read_text(encoding='utf-8')
            analysis = json.loads(bundle.analysis_path.read_text(encoding='utf-8'))
            manifest = json.loads(bundle.manifest_path.read_text(encoding='utf-8'))

        self.assertIn('<title>Agent Trace Studio</title>', html)
        self.assertIn('<h1 id="dashboard-title">Agent Trace Studio</h1>', html)
        self.assertEqual(analysis['meta']['title'], 'Agent Trace Studio')
        self.assertEqual(analysis['meta']['trace_set_title'], 'Async Cancellation Agent Run')
        self.assertEqual(manifest['title'], 'Agent Trace Studio')
        self.assertEqual(manifest['trace_set_title'], 'Async Cancellation Agent Run')

    def test_exports_normalized_tool_breakdown(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            journal = root / 'session.jsonl'
            write_journal(journal)
            result = analyze_journals([journal])

            bundle = write_report(result, output_dir=root / 'dashboard')
            with bundle.turns_csv_path.open(encoding='utf-8') as stream:
                rows = list(csv.DictReader(stream))

        self.assertEqual(json.loads(rows[0]['tool_breakdown']), {'exec_command': 1})
        self.assertEqual(json.loads(rows[1]['tool_breakdown']), {'apply_patch': 1, 'exec_command': 1, 'search': 1})


if __name__ == '__main__':
    unittest.main()
